// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2UV2DQ_SVdYh2Qoni6aXWtXwvqNiqKn0',
    appId: '1:940449335995:web:d859944952f79ededa779e',
    messagingSenderId: '940449335995',
    projectId: 'fir-flutter-codelab-c8a24',
    authDomain: 'fir-flutter-codelab-c8a24.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c8a24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENUvGj1KzDLN5AhQN56YEhFxFsRfz3NI',
    appId: '1:940449335995:android:0ec8080df12d0603da779e',
    messagingSenderId: '940449335995',
    projectId: 'fir-flutter-codelab-c8a24',
    storageBucket: 'fir-flutter-codelab-c8a24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7MKXavRO5fZlhRg4mKIMbCM4y-rtxOds',
    appId: '1:940449335995:ios:437a1c9479d758c1da779e',
    messagingSenderId: '940449335995',
    projectId: 'fir-flutter-codelab-c8a24',
    storageBucket: 'fir-flutter-codelab-c8a24.appspot.com',
    iosClientId: '940449335995-iagkiebn2boj8mdmh23u2bjue7feb2vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7MKXavRO5fZlhRg4mKIMbCM4y-rtxOds',
    appId: '1:940449335995:ios:437a1c9479d758c1da779e',
    messagingSenderId: '940449335995',
    projectId: 'fir-flutter-codelab-c8a24',
    storageBucket: 'fir-flutter-codelab-c8a24.appspot.com',
    iosClientId: '940449335995-iagkiebn2boj8mdmh23u2bjue7feb2vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
